services:
  backapp:
    image: cubix-backapp:hw
    environment:
      CUBIX_HOMEWORK: "Levente Pápes"
      APP_DEFAULT_MESSAGE: ""
    expose:
      - "8080"

  frontapp:
    image: cubix-frontapp:hw
    environment:
      CUBIX_HOMEWORK: "Levente Pápes"
      APP_DEFAULT_MESSAGE: ""
      BACK_URL: "http://backapp:8080"
    ports:
      - "8080:8080"
